version: "3.10"
services:
  api:
    ports:
    - "8000:8000"
    image: 4surpr1se/stripe_api
    volumes:
      - api:/app
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  api:
